/*
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#include "AssignKeyZones.hpp"

QMap<int, QString> assignKeyZones(const QString &layout)
{
  QMap<int, QString> mappings;
  
  if ( layout == "de" || layout == "deutsch" )
  {
    // QWERTZ layout (German)
    mappings[0] = "Strg"; // Ctrl
    mappings[1] = "Unbekannt"; // Unused/Unknown
    mappings[2] = "Fn";
    mappings[3] = "⊞";
    mappings[4] = "Alt";
    mappings[5] = "Unbekannt";
    mappings[6] = "Unbekannt";
    mappings[7] = "Leertaste"; // Space
    mappings[8] = "Unbekannt";
    mappings[9] = "Unbekannt";
    mappings[10] = "Alt";
    mappings[11] = "Unbekannt";
    mappings[12] = "Strg";
    mappings[13] = "←";
    mappings[14] = "↑";
    mappings[15] = "→";
    mappings[16] = "0";
    mappings[17] = ",";
    mappings[18] = "↓";
    mappings[19] = "Unbekannt";
    mappings[20] = "Unbekannt";
    mappings[21] = "Unbekannt";
    mappings[22] = "⇧"; // Shift
    mappings[23] = "<";
    mappings[24] = "Y";
    mappings[25] = "X";
    mappings[26] = "C";
    mappings[27] = "V";
    mappings[28] = "B";
    mappings[29] = "N";
    mappings[30] = "M";
    mappings[31] = ",";
    mappings[32] = ".";
    mappings[33] = "-";
    mappings[34] = "Unbekannt";
    mappings[35] = "⇧";
    mappings[36] = "1";
    mappings[37] = "2";
    mappings[38] = "3";
    mappings[39] = "↵"; // Enter
    mappings[40] = "Unbekannt";
    mappings[41] = "Unbekannt";
    mappings[42] = "Feststelltaste"; // Caps
    mappings[43] = "Unbekannt";
    mappings[44] = "A";
    mappings[45] = "S";
    mappings[46] = "D";
    mappings[47] = "F";
    mappings[48] = "G";
    mappings[49] = "H";
    mappings[50] = "J";
    mappings[51] = "K";
    mappings[52] = "L";
    mappings[53] = "Ö";
    mappings[54] = "Ä";
    mappings[55] = "#";
    mappings[56] = "Unbekannt";
    mappings[57] = "4";
    mappings[58] = "5";
    mappings[59] = "6";
    mappings[60] = "Unbekannt";
    mappings[61] = "Unbekannt";
    mappings[62] = "Unbekannt";
    mappings[63] = "Tab";
    mappings[64] = "Unbekannt";
    mappings[65] = "Q";
    mappings[66] = "W";
    mappings[67] = "E";
    mappings[68] = "R";
    mappings[69] = "T";
    mappings[70] = "Z";
    mappings[71] = "U";
    mappings[72] = "I";
    mappings[73] = "O";
    mappings[74] = "P";
    mappings[75] = "Ü";
    mappings[76] = "+";
    mappings[77] = "↵";
    mappings[78] = "7";
    mappings[79] = "8";
    mappings[80] = "9";
    mappings[81] = "+";
    mappings[82] = "Unbekannt";
    mappings[83] = "Unbekannt";
    mappings[84] = "^";
    mappings[85] = "1";
    mappings[86] = "2";
    mappings[87] = "3";
    mappings[88] = "4";
    mappings[89] = "5";
    mappings[90] = "6";
    mappings[91] = "7";
    mappings[92] = "8";
    mappings[93] = "9";
    mappings[94] = "0";
    mappings[95] = "ß";
    mappings[96] = "'";
    mappings[97] = "Unbekannt";
    mappings[98] = "⌫"; // Backspace
    mappings[99] = "Num";
    mappings[100] = "/";
    mappings[101] = "*";
    mappings[102] = "-";
    mappings[103] = "Unbekannt";
    mappings[104] = "Unbekannt";
    mappings[105] = "Esc";
    mappings[106] = "F1";
    mappings[107] = "F2";
    mappings[108] = "F3";
    mappings[109] = "F4";
    mappings[110] = "F5";
    mappings[111] = "F6";
    mappings[112] = "F7";
    mappings[113] = "F8";
    mappings[114] = "F9";
    mappings[115] = "F10";
    mappings[116] = "F11";
    mappings[117] = "F12";
    mappings[118] = "Druck"; // PrtSc
    mappings[119] = "Einfg"; // Ins
    mappings[120] = "Entf"; // Del
    mappings[121] = "Pos1"; // Home
    mappings[122] = "Ende"; // End
    mappings[123] = "Bild↑"; // PgUp
    mappings[124] = "Bild↓"; // PgDn
    mappings[125] = "Unbekannt";
  }
  else if ( layout == "tr" || layout == "turkish" || layout == "türkçe" )
  {
    // Turkish Q layout
    mappings[0] = "Strg"; // Ctrl
    mappings[1] = "Unbekannt"; // Unused/Unknown
    mappings[2] = "Fn";
    mappings[3] = "⊞";
    mappings[4] = "Alt";
    mappings[5] = "Unbekannt";
    mappings[6] = "Unbekannt";
    mappings[7] = "Boşluk"; // Space
    mappings[8] = "Unbekannt";
    mappings[9] = "Unbekannt";
    mappings[10] = "Alt";
    mappings[11] = "Unbekannt";
    mappings[12] = "Strg";
    mappings[13] = "←";
    mappings[14] = "↑";
    mappings[15] = "→";
    mappings[16] = "0";
    mappings[17] = ",";
    mappings[18] = "↓";
    mappings[19] = "Unbekannt";
    mappings[20] = "Unbekannt";
    mappings[21] = "Unbekannt";
    mappings[22] = "⇧"; // Shift
    mappings[23] = "<";
    mappings[24] = "Z";
    mappings[25] = "X";
    mappings[26] = "C";
    mappings[27] = "V";
    mappings[28] = "B";
    mappings[29] = "N";
    mappings[30] = "M";
    mappings[31] = ",";
    mappings[32] = ".";
    mappings[33] = "-";
    mappings[34] = "Unbekannt";
    mappings[35] = "⇧";
    mappings[36] = "1";
    mappings[37] = "2";
    mappings[38] = "3";
    mappings[39] = "↵"; // Enter
    mappings[40] = "Unbekannt";
    mappings[41] = "Unbekannt";
    mappings[42] = "Caps";
    mappings[43] = "Unbekannt";
    mappings[44] = "A";
    mappings[45] = "S";
    mappings[46] = "D";
    mappings[47] = "F";
    mappings[48] = "G";
    mappings[49] = "H";
    mappings[50] = "J";
    mappings[51] = "K";
    mappings[52] = "L";
    mappings[53] = "Ş";
    mappings[54] = "İ";
    mappings[55] = "Ğ";
    mappings[56] = "Unbekannt";
    mappings[57] = "4";
    mappings[58] = "5";
    mappings[59] = "6";
    mappings[60] = "Unbekannt";
    mappings[61] = "Unbekannt";
    mappings[62] = "Unbekannt";
    mappings[63] = "Tab";
    mappings[64] = "Unbekannt";
    mappings[65] = "Q";
    mappings[66] = "W";
    mappings[67] = "E";
    mappings[68] = "R";
    mappings[69] = "T";
    mappings[70] = "Y";
    mappings[71] = "U";
    mappings[72] = "I";
    mappings[73] = "O";
    mappings[74] = "P";
    mappings[75] = "Ü";
    mappings[76] = "Ç";
    mappings[77] = "↵";
    mappings[78] = "7";
    mappings[79] = "8";
    mappings[80] = "9";
    mappings[81] = "+";
    mappings[82] = "Unbekannt";
    mappings[83] = "Unbekannt";
    mappings[84] = "\""; // Quote
    mappings[85] = "1";
    mappings[86] = "2";
    mappings[87] = "3";
    mappings[88] = "4";
    mappings[89] = "5";
    mappings[90] = "6";
    mappings[91] = "7";
    mappings[92] = "8";
    mappings[93] = "9";
    mappings[94] = "0";
    mappings[95] = "*";
    mappings[96] = "-";
    mappings[97] = "Unbekannt";
    mappings[98] = "⌫"; // Backspace
    mappings[99] = "Num";
    mappings[100] = "/";
    mappings[101] = "*";
    mappings[102] = "-";
    mappings[103] = "Unbekannt";
    mappings[104] = "Unbekannt";
    mappings[105] = "Esc";
    mappings[106] = "F1";
    mappings[107] = "F2";
    mappings[108] = "F3";
    mappings[109] = "F4";
    mappings[110] = "F5";
    mappings[111] = "F6";
    mappings[112] = "F7";
    mappings[113] = "F8";
    mappings[114] = "F9";
    mappings[115] = "F10";
    mappings[116] = "F11";
    mappings[117] = "F12";
    mappings[118] = "PrtSc";
    mappings[119] = "Ins";
    mappings[120] = "Del";
    mappings[121] = "Home";
    mappings[122] = "End";
    mappings[123] = "PgUp";
    mappings[124] = "PgDn";
    mappings[125] = "Unbekannt";
  }
  else if ( layout == "fr" || layout == "french" || layout == "français" )
  {
    // French AZERTY layout
    mappings[0] = "Ctrl";
    mappings[1] = "Inconnu"; // Unused/Unknown
    mappings[2] = "Fn";
    mappings[3] = "⊞";
    mappings[4] = "Alt";
    mappings[5] = "Inconnu";
    mappings[6] = "Inconnu";
    mappings[7] = "Espace"; // Space
    mappings[8] = "Inconnu";
    mappings[9] = "Inconnu";
    mappings[10] = "Alt";
    mappings[11] = "Inconnu";
    mappings[12] = "Ctrl";
    mappings[13] = "←";
    mappings[14] = "↑";
    mappings[15] = "→";
    mappings[16] = "0";
    mappings[17] = ",";
    mappings[18] = "↓";
    mappings[19] = "Inconnu";
    mappings[20] = "Inconnu";
    mappings[21] = "Inconnu";
    mappings[22] = "⇧"; // Shift
    mappings[23] = "<";
    mappings[24] = "W"; // Z position in AZERTY
    mappings[25] = "X";
    mappings[26] = "C";
    mappings[27] = "V";
    mappings[28] = "B";
    mappings[29] = "N";
    mappings[30] = ",";
    mappings[31] = ";";
    mappings[32] = ":";
    mappings[33] = "=";
    mappings[34] = "Inconnu";
    mappings[35] = "⇧";
    mappings[36] = "&";
    mappings[37] = "é";
    mappings[38] = "\"";
    mappings[39] = "↵"; // Enter
    mappings[40] = "Inconnu";
    mappings[41] = "Inconnu";
    mappings[42] = "Verr Maj"; // Caps
    mappings[43] = "Inconnu";
    mappings[44] = "Q"; // A position in AZERTY
    mappings[45] = "S";
    mappings[46] = "D";
    mappings[47] = "F";
    mappings[48] = "G";
    mappings[49] = "H";
    mappings[50] = "J";
    mappings[51] = "K";
    mappings[52] = "L";
    mappings[53] = "M"; // ; position in AZERTY
    mappings[54] = "ù";
    mappings[55] = "^";
    mappings[56] = "Inconnu";
    mappings[57] = "'";
    mappings[58] = "(";
    mappings[59] = "-";
    mappings[60] = "Inconnu";
    mappings[61] = "Inconnu";
    mappings[62] = "Inconnu";
    mappings[63] = "Tab";
    mappings[64] = "Inconnu";
    mappings[65] = "A"; // Q position in AZERTY
    mappings[66] = "Z"; // W position in AZERTY
    mappings[67] = "E";
    mappings[68] = "R";
    mappings[69] = "T";
    mappings[70] = "Y";
    mappings[71] = "U";
    mappings[72] = "I";
    mappings[73] = "O";
    mappings[74] = "P";
    mappings[75] = ")";
    mappings[76] = "=";
    mappings[77] = "↵";
    mappings[78] = "à";
    mappings[79] = "_";
    mappings[80] = "ç";
    mappings[81] = "+";
    mappings[82] = "Inconnu";
    mappings[83] = "Inconnu";
    mappings[84] = "²"; // `
    mappings[85] = "&";
    mappings[86] = "é";
    mappings[87] = "\"";
    mappings[88] = "'";
    mappings[89] = "(";
    mappings[90] = "-";
    mappings[91] = "è";
    mappings[92] = "_";
    mappings[93] = "ç";
    mappings[94] = "à";
    mappings[95] = ")";
    mappings[96] = "=";
    mappings[97] = "Inconnu";
    mappings[98] = "⌫"; // Backspace
    mappings[99] = "Num";
    mappings[100] = "/";
    mappings[101] = "*";
    mappings[102] = "-";
    mappings[103] = "Inconnu";
    mappings[104] = "Inconnu";
    mappings[105] = "Esc";
    mappings[106] = "F1";
    mappings[107] = "F2";
    mappings[108] = "F3";
    mappings[109] = "F4";
    mappings[110] = "F5";
    mappings[111] = "F6";
    mappings[112] = "F7";
    mappings[113] = "F8";
    mappings[114] = "F9";
    mappings[115] = "F10";
    mappings[116] = "F11";
    mappings[117] = "F12";
    mappings[118] = "Imp écr"; // PrtSc
    mappings[119] = "Ins";
    mappings[120] = "Suppr"; // Del
    mappings[121] = "Début"; // Home
    mappings[122] = "Fin"; // End
    mappings[123] = "Page↑"; // PgUp
    mappings[124] = "Page↓"; // PgDn
    mappings[125] = "Inconnu";
  }
  else if ( layout == "es" || layout == "spanish" || layout == "español" )
  {
    // Spanish QWERTY layout
    mappings[0] = "Ctrl";
    mappings[1] = "Desconocido"; // Unused/Unknown
    mappings[2] = "Fn";
    mappings[3] = "⊞";
    mappings[4] = "Alt";
    mappings[5] = "Desconocido";
    mappings[6] = "Desconocido";
    mappings[7] = "Espacio"; // Space
    mappings[8] = "Desconocido";
    mappings[9] = "Desconocido";
    mappings[10] = "Alt";
    mappings[11] = "Desconocido";
    mappings[12] = "Ctrl";
    mappings[13] = "←";
    mappings[14] = "↑";
    mappings[15] = "→";
    mappings[16] = "0";
    mappings[17] = ",";
    mappings[18] = "↓";
    mappings[19] = "Desconocido";
    mappings[20] = "Desconocido";
    mappings[21] = "Desconocido";
    mappings[22] = "⇧"; // Shift
    mappings[23] = "<";
    mappings[24] = "Z";
    mappings[25] = "X";
    mappings[26] = "C";
    mappings[27] = "V";
    mappings[28] = "B";
    mappings[29] = "N";
    mappings[30] = "M";
    mappings[31] = ",";
    mappings[32] = ".";
    mappings[33] = "-";
    mappings[34] = "Desconocido";
    mappings[35] = "⇧";
    mappings[36] = "1";
    mappings[37] = "2";
    mappings[38] = "3";
    mappings[39] = "↵"; // Enter
    mappings[40] = "Desconocido";
    mappings[41] = "Desconocido";
    mappings[42] = "Bloq Mayús"; // Caps
    mappings[43] = "Desconocido";
    mappings[44] = "A";
    mappings[45] = "S";
    mappings[46] = "D";
    mappings[47] = "F";
    mappings[48] = "G";
    mappings[49] = "H";
    mappings[50] = "J";
    mappings[51] = "K";
    mappings[52] = "L";
    mappings[53] = "Ñ";
    mappings[54] = "'";
    mappings[55] = "Ç";
    mappings[56] = "Desconocido";
    mappings[57] = "4";
    mappings[58] = "5";
    mappings[59] = "6";
    mappings[60] = "Desconocido";
    mappings[61] = "Desconocido";
    mappings[62] = "Desconocido";
    mappings[63] = "Tab";
    mappings[64] = "Desconocido";
    mappings[65] = "Q";
    mappings[66] = "W";
    mappings[67] = "E";
    mappings[68] = "R";
    mappings[69] = "T";
    mappings[70] = "Y";
    mappings[71] = "U";
    mappings[72] = "I";
    mappings[73] = "O";
    mappings[74] = "P";
    mappings[75] = "`";
    mappings[76] = "+";
    mappings[77] = "↵";
    mappings[78] = "7";
    mappings[79] = "8";
    mappings[80] = "9";
    mappings[81] = "+";
    mappings[82] = "Desconocido";
    mappings[83] = "Desconocido";
    mappings[84] = "º"; // `
    mappings[85] = "1";
    mappings[86] = "2";
    mappings[87] = "3";
    mappings[88] = "4";
    mappings[89] = "5";
    mappings[90] = "6";
    mappings[91] = "7";
    mappings[92] = "8";
    mappings[93] = "9";
    mappings[94] = "0";
    mappings[95] = "'";
    mappings[96] = "¡";
    mappings[97] = "Desconocido";
    mappings[98] = "⌫"; // Backspace
    mappings[99] = "Num";
    mappings[100] = "/";
    mappings[101] = "*";
    mappings[102] = "-";
    mappings[103] = "Desconocido";
    mappings[104] = "Desconocido";
    mappings[105] = "Esc";
    mappings[106] = "F1";
    mappings[107] = "F2";
    mappings[108] = "F3";
    mappings[109] = "F4";
    mappings[110] = "F5";
    mappings[111] = "F6";
    mappings[112] = "F7";
    mappings[113] = "F8";
    mappings[114] = "F9";
    mappings[115] = "F10";
    mappings[116] = "F11";
    mappings[117] = "F12";
    mappings[118] = "Imp Pant"; // PrtSc
    mappings[119] = "Ins";
    mappings[120] = "Supr"; // Del
    mappings[121] = "Inicio"; // Home
    mappings[122] = "Fin"; // End
    mappings[123] = "Re Pág"; // PgUp
    mappings[124] = "Av Pág"; // PgDn
    mappings[125] = "Desconocido";
  }
  else if ( layout == "it" || layout == "italian" || layout == "italiano" )
  {
    // Italian QWERTY layout
    mappings[0] = "Ctrl";
    mappings[1] = "Sconosciuto"; // Unused/Unknown
    mappings[2] = "Fn";
    mappings[3] = "⊞";
    mappings[4] = "Alt";
    mappings[5] = "Sconosciuto";
    mappings[6] = "Sconosciuto";
    mappings[7] = "Spazio"; // Space
    mappings[8] = "Sconosciuto";
    mappings[9] = "Sconosciuto";
    mappings[10] = "Alt";
    mappings[11] = "Sconosciuto";
    mappings[12] = "Ctrl";
    mappings[13] = "←";
    mappings[14] = "↑";
    mappings[15] = "→";
    mappings[16] = "0";
    mappings[17] = ",";
    mappings[18] = "↓";
    mappings[19] = "Sconosciuto";
    mappings[20] = "Sconosciuto";
    mappings[21] = "Sconosciuto";
    mappings[22] = "⇧"; // Shift
    mappings[23] = "<";
    mappings[24] = "Z";
    mappings[25] = "X";
    mappings[26] = "C";
    mappings[27] = "V";
    mappings[28] = "B";
    mappings[29] = "N";
    mappings[30] = "M";
    mappings[31] = ",";
    mappings[32] = ".";
    mappings[33] = "-";
    mappings[34] = "Sconosciuto";
    mappings[35] = "⇧";
    mappings[36] = "1";
    mappings[37] = "2";
    mappings[38] = "3";
    mappings[39] = "↵"; // Enter
    mappings[40] = "Sconosciuto";
    mappings[41] = "Sconosciuto";
    mappings[42] = "Bloc Maiusc"; // Caps
    mappings[43] = "Sconosciuto";
    mappings[44] = "A";
    mappings[45] = "S";
    mappings[46] = "D";
    mappings[47] = "F";
    mappings[48] = "G";
    mappings[49] = "H";
    mappings[50] = "J";
    mappings[51] = "K";
    mappings[52] = "L";
    mappings[53] = "ò";
    mappings[54] = "à";
    mappings[55] = "ù";
    mappings[56] = "Sconosciuto";
    mappings[57] = "4";
    mappings[58] = "5";
    mappings[59] = "6";
    mappings[60] = "Sconosciuto";
    mappings[61] = "Sconosciuto";
    mappings[62] = "Sconosciuto";
    mappings[63] = "Tab";
    mappings[64] = "Sconosciuto";
    mappings[65] = "Q";
    mappings[66] = "W";
    mappings[67] = "E";
    mappings[68] = "R";
    mappings[69] = "T";
    mappings[70] = "Y";
    mappings[71] = "U";
    mappings[72] = "I";
    mappings[73] = "O";
    mappings[74] = "P";
    mappings[75] = "è";
    mappings[76] = "+";
    mappings[77] = "↵";
    mappings[78] = "7";
    mappings[79] = "8";
    mappings[80] = "9";
    mappings[81] = "+";
    mappings[82] = "Sconosciuto";
    mappings[83] = "Sconosciuto";
    mappings[84] = "\\"; // `
    mappings[85] = "1";
    mappings[86] = "2";
    mappings[87] = "3";
    mappings[88] = "4";
    mappings[89] = "5";
    mappings[90] = "6";
    mappings[91] = "7";
    mappings[92] = "8";
    mappings[93] = "9";
    mappings[94] = "0";
    mappings[95] = "'";
    mappings[96] = "ì";
    mappings[97] = "Sconosciuto";
    mappings[98] = "⌫"; // Backspace
    mappings[99] = "Num";
    mappings[100] = "/";
    mappings[101] = "*";
    mappings[102] = "-";
    mappings[103] = "Sconosciuto";
    mappings[104] = "Sconosciuto";
    mappings[105] = "Esc";
    mappings[106] = "F1";
    mappings[107] = "F2";
    mappings[108] = "F3";
    mappings[109] = "F4";
    mappings[110] = "F5";
    mappings[111] = "F6";
    mappings[112] = "F7";
    mappings[113] = "F8";
    mappings[114] = "F9";
    mappings[115] = "F10";
    mappings[116] = "F11";
    mappings[117] = "F12";
    mappings[118] = "Stamp"; // PrtSc
    mappings[119] = "Ins";
    mappings[120] = "Canc"; // Del
    mappings[121] = "Home";
    mappings[122] = "Fine"; // End
    mappings[123] = "Pag↑"; // PgUp
    mappings[124] = "Pag↓"; // PgDn
    mappings[125] = "Sconosciuto";
  }
  else if ( layout == "ar" || layout == "arabic" || layout == "العربية" )
  {
    // Arabic layout (based on QWERTY with Arabic characters)
    mappings[0] = "Ctrl";
    mappings[1] = "غير معروف"; // Unused/Unknown
    mappings[2] = "Fn";
    mappings[3] = "⊞";
    mappings[4] = "Alt";
    mappings[5] = "غير معروف";
    mappings[6] = "غير معروف";
    mappings[7] = "مسافة"; // Space
    mappings[8] = "غير معروف";
    mappings[9] = "غير معروف";
    mappings[10] = "Alt";
    mappings[11] = "غير معروف";
    mappings[12] = "Ctrl";
    mappings[13] = "←";
    mappings[14] = "↑";
    mappings[15] = "→";
    mappings[16] = "0";
    mappings[17] = ",";
    mappings[18] = "↓";
    mappings[19] = "غير معروف";
    mappings[20] = "غير معروف";
    mappings[21] = "غير معروف";
    mappings[22] = "⇧"; // Shift
    mappings[23] = "<";
    mappings[24] = "ز"; // Z
    mappings[25] = "ش"; // X
    mappings[26] = "س"; // C
    mappings[27] = "ي"; // V
    mappings[28] = "ل"; // B
    mappings[29] = "ن"; // N
    mappings[30] = "م"; // M
    mappings[31] = ",";
    mappings[32] = ".";
    mappings[33] = "-";
    mappings[34] = "غير معروف";
    mappings[35] = "⇧";
    mappings[36] = "1";
    mappings[37] = "2";
    mappings[38] = "3";
    mappings[39] = "↵"; // Enter
    mappings[40] = "غير معروف";
    mappings[41] = "غير معروف";
    mappings[42] = "Caps";
    mappings[43] = "غير معروف";
    mappings[44] = "ا"; // A
    mappings[45] = "س"; // S
    mappings[46] = "د"; // D
    mappings[47] = "ف"; // F
    mappings[48] = "غ"; // G
    mappings[49] = "ه"; // H
    mappings[50] = "ج"; // J
    mappings[51] = "ك"; // K
    mappings[52] = "ل"; // L
    mappings[53] = "؛"; // ;
    mappings[54] = "'"; // '
    mappings[55] = "خ"; // #
    mappings[56] = "غير معروف";
    mappings[57] = "4";
    mappings[58] = "5";
    mappings[59] = "6";
    mappings[60] = "غير معروف";
    mappings[61] = "غير معروف";
    mappings[62] = "غير معروف";
    mappings[63] = "Tab";
    mappings[64] = "غير معروف";
    mappings[65] = "ض"; // Q
    mappings[66] = "ص"; // W
    mappings[67] = "ث"; // E
    mappings[68] = "ق"; // R
    mappings[69] = "ف"; // T
    mappings[70] = "غ"; // Y
    mappings[71] = "ع"; // U
    mappings[72] = "ه"; // I
    mappings[73] = "خ"; // O
    mappings[74] = "ح"; // P
    mappings[75] = "ج"; // [
    mappings[76] = "د"; // ]
    mappings[77] = "↵";
    mappings[78] = "7";
    mappings[79] = "8";
    mappings[80] = "9";
    mappings[81] = "+";
    mappings[82] = "غير معروف";
    mappings[83] = "غير معروف";
    mappings[84] = "`"; // `
    mappings[85] = "1";
    mappings[86] = "2";
    mappings[87] = "3";
    mappings[88] = "4";
    mappings[89] = "5";
    mappings[90] = "6";
    mappings[91] = "7";
    mappings[92] = "8";
    mappings[93] = "9";
    mappings[94] = "0";
    mappings[95] = "-";
    mappings[96] = "=";
    mappings[97] = "غير معروف";
    mappings[98] = "⌫"; // Backspace
    mappings[99] = "Num";
    mappings[100] = "/";
    mappings[101] = "*";
    mappings[102] = "-";
    mappings[103] = "غير معروف";
    mappings[104] = "غير معروف";
    mappings[105] = "Esc";
    mappings[106] = "F1";
    mappings[107] = "F2";
    mappings[108] = "F3";
    mappings[109] = "F4";
    mappings[110] = "F5";
    mappings[111] = "F6";
    mappings[112] = "F7";
    mappings[113] = "F8";
    mappings[114] = "F9";
    mappings[115] = "F10";
    mappings[116] = "F11";
    mappings[117] = "F12";
    mappings[118] = "PrtSc";
    mappings[119] = "Ins";
    mappings[120] = "Del";
    mappings[121] = "Home";
    mappings[122] = "End";
    mappings[123] = "PgUp";
    mappings[124] = "PgDn";
    mappings[125] = "غير معروف";
  }
  else
  {
    // Default to QWERTY (US/English)
    mappings[0] = "Ctrl";
    mappings[1] = "Unused/Unknown";
    mappings[2] = "Fn";
    mappings[3] = "⊞";
    mappings[4] = "Alt";
    mappings[5] = "Unused/Unknown";
    mappings[6] = "Unused/Unknown";
    mappings[7] = "Space";
    mappings[8] = "Unused/Unknown";
    mappings[9] = "Unused/Unknown";
    mappings[10] = "Alt";
    mappings[11] = "Unused/Unknown";
    mappings[12] = "Ctrl";
    mappings[13] = "←";
    mappings[14] = "↑";
    mappings[15] = "→";
    mappings[16] = "0";
    mappings[17] = ",";
    mappings[18] = "↓";
    mappings[19] = "Unused/Unknown";
    mappings[20] = "Unused/Unknown";
    mappings[21] = "Unused/Unknown";
    mappings[22] = "⇧";
    mappings[23] = "<";
    mappings[24] = "Z"; // Swapped with Y
    mappings[25] = "X";
    mappings[26] = "C";
    mappings[27] = "V";
    mappings[28] = "B";
    mappings[29] = "N";
    mappings[30] = "M";
    mappings[31] = ",";
    mappings[32] = ".";
    mappings[33] = "-";
    mappings[34] = "Unused/Unknown";
    mappings[35] = "⇧";
    mappings[36] = "1";
    mappings[37] = "2";
    mappings[38] = "3";
    mappings[39] = "↵";
    mappings[40] = "Unused/Unknown";
    mappings[41] = "Unused/Unknown";
    mappings[42] = "Caps";
    mappings[43] = "Unused/Unknown";
    mappings[44] = "A";
    mappings[45] = "S";
    mappings[46] = "D";
    mappings[47] = "F";
    mappings[48] = "G";
    mappings[49] = "H";
    mappings[50] = "J";
    mappings[51] = "K";
    mappings[52] = "L";
    mappings[53] = ";"; // Instead of Ö
    mappings[54] = "'"; // Instead of Ä
    mappings[55] = "#";
    mappings[56] = "Unused/Unknown";
    mappings[57] = "4";
    mappings[58] = "5";
    mappings[59] = "6";
    mappings[60] = "Unused/Unknown";
    mappings[61] = "Unused/Unknown";
    mappings[62] = "Unused/Unknown";
    mappings[63] = "Tab";
    mappings[64] = "Unused/Unknown";
    mappings[65] = "Q";
    mappings[66] = "W";
    mappings[67] = "E";
    mappings[68] = "R";
    mappings[69] = "T";
    mappings[70] = "Y"; // Swapped with Z
    mappings[71] = "U";
    mappings[72] = "I";
    mappings[73] = "O";
    mappings[74] = "P";
    mappings[75] = "["; // Instead of Ü
    mappings[76] = "]"; // Instead of +
    mappings[77] = "↵";
    mappings[78] = "7";
    mappings[79] = "8";
    mappings[80] = "9";
    mappings[81] = "+";
    mappings[82] = "Unused/Unknown";
    mappings[83] = "Unused/Unknown";
    mappings[84] = "`"; // Instead of ^
    mappings[85] = "1";
    mappings[86] = "2";
    mappings[87] = "3";
    mappings[88] = "4";
    mappings[89] = "5";
    mappings[90] = "6";
    mappings[91] = "7";
    mappings[92] = "8";
    mappings[93] = "9";
    mappings[94] = "0";
    mappings[95] = "-"; // Instead of ß
    mappings[96] = "="; // Instead of '
    mappings[97] = "Unused/Unknown";
    mappings[98] = "⌫";
    mappings[99] = "Num";
    mappings[100] = "/";
    mappings[101] = "*";
    mappings[102] = "-";
    mappings[103] = "Unused/Unknown";
    mappings[104] = "Unused/Unknown";
    mappings[105] = "Esc";
    mappings[106] = "F1";
    mappings[107] = "F2";
    mappings[108] = "F3";
    mappings[109] = "F4";
    mappings[110] = "F5";
    mappings[111] = "F6";
    mappings[112] = "F7";
    mappings[113] = "F8";
    mappings[114] = "F9";
    mappings[115] = "F10";
    mappings[116] = "F11";
    mappings[117] = "F12";
    mappings[118] = "PrtSc";
    mappings[119] = "Ins";
    mappings[120] = "Del";
    mappings[121] = "Home";
    mappings[122] = "End";
    mappings[123] = "PgUp";
    mappings[124] = "PgDn";
    mappings[125] = "Unused/Unknown";
  }
  
  return mappings;
}