/*
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once

#include <cmath>
#include <cstdint>
#include <string>
#include <vector>

namespace ucc::hal
{

// ---------------------------------------------------------------------------
//  Fan device classification
// ---------------------------------------------------------------------------

/**
 * @brief Physical type of a fan device.
 *
 * Providers set this during enumerateFans() so the auto-zone algorithm
 * can pick sensible defaults (e.g. pumps get a flat curve, staged fans
 * skip PWM writes).
 */
enum class FanDeviceType : uint8_t
{
  Fan,         ///< Standard axial / PWM fan (case, CPU tower, radiator)
  Pump,        ///< AIO or custom-loop pump (PWM, continuous 0–100%)
  Staged,      ///< Firmware-level fan with discrete speed stages (laptop WMI)
  StagedPump,  ///< Pump with discrete voltage levels (e.g. BLE water cooler)
  Virtual,     ///< GPU fan controlled via NVML, not via hwmon PWM
  Unknown
};

inline std::string fanDeviceTypeToString( FanDeviceType t ) noexcept
{
  switch ( t )
  {
    case FanDeviceType::Fan:        return "fan";
    case FanDeviceType::Pump:       return "pump";
    case FanDeviceType::Staged:     return "staged";
    case FanDeviceType::StagedPump: return "stagedPump";
    case FanDeviceType::Virtual:    return "virtual";
    case FanDeviceType::Unknown:    return "unknown";
  }
  return "unknown";
}

inline FanDeviceType fanDeviceTypeFromString( const std::string &s ) noexcept
{
  if ( s == "fan" )        return FanDeviceType::Fan;
  if ( s == "pump" )       return FanDeviceType::Pump;
  if ( s == "staged" )     return FanDeviceType::Staged;
  if ( s == "stagedPump" ) return FanDeviceType::StagedPump;
  if ( s == "virtual" )    return FanDeviceType::Virtual;
  return FanDeviceType::Unknown;
}

// ---------------------------------------------------------------------------
//  Thermal source — what drives a fan zone's curve
// ---------------------------------------------------------------------------

/**
 * @brief How multiple sensors are combined into a single temperature reading.
 */
enum class ThermalStrategy : uint8_t
{
  Single,            ///< One sensor, sensorIds[0]
  Max,               ///< max(all sensors) — "hottest component"
  Average,           ///< Arithmetic mean over all readable sensors
  WeightedAvg,       ///< Weighted average (weights[] parallel to sensorIds[])
  Percentile90,      ///< 90th percentile of readable sensor temperatures
  SafetyClampedAvg,  ///< Average unless hottest sensor crosses threshold, then use max
};

inline std::string thermalStrategyToString( ThermalStrategy s ) noexcept
{
  switch ( s )
  {
    case ThermalStrategy::Single:           return "single";
    case ThermalStrategy::Max:              return "max";
    case ThermalStrategy::Average:          return "average";
    case ThermalStrategy::WeightedAvg:      return "weightedAvg";
    case ThermalStrategy::Percentile90:     return "percentile90";
    case ThermalStrategy::SafetyClampedAvg: return "safetyClampedAvg";
  }
  return "single";
}

inline ThermalStrategy thermalStrategyFromString( const std::string &s ) noexcept
{
  if ( s == "max" )               return ThermalStrategy::Max;
  if ( s == "average" )           return ThermalStrategy::Average;
  if ( s == "weightedAvg" )       return ThermalStrategy::WeightedAvg;
  if ( s == "percentile90" )      return ThermalStrategy::Percentile90;
  if ( s == "safetyClampedAvg" )  return ThermalStrategy::SafetyClampedAvg;
  return ThermalStrategy::Single;
}

/**
 * @brief A temperature source that feeds a fan zone.
 *
 * Can wrap a single hw sensor or combine several (e.g. max of CPU + GPU
 * for case fans, or a weighted blend for a shared radiator).
 *
 * Built-in sources ("cpu", "gpu", "hottest") are auto-generated by
 * HardwareManager after detection.  Users can create custom sources
 * in the GUI and store them in the profile.
 */
struct ThermalSource
{
  std::string id;               ///< "cpu", "gpu", "hottest", "custom-1", ...
  std::string label;            ///< "CPU", "GPU", "Hottest Component", ...
  ThermalStrategy strategy = ThermalStrategy::Single;
  std::vector< std::string > sensorIds; ///< TempSensorInfo::id references
  std::vector< double > weights;        ///< Only for WeightedAvg (same length as sensorIds)
};

// ---------------------------------------------------------------------------
//  Fan curve entry (re-uses existing FanTableEntry layout)
// ---------------------------------------------------------------------------

/**
 * @brief A single temp → speed mapping point.
 *
 * Identical to the existing FanTableEntry but placed here for reference.
 * FanZone::curve uses std::vector< FanCurvePoint > for its temp-to-speed map.
 */
struct FanCurvePoint
{
  int32_t temp  = 0;   ///< °C
  int32_t speed = 0;   ///< 0–100 %

  FanCurvePoint() = default;
  FanCurvePoint( int32_t t, int32_t s ) : temp( t ), speed( s ) {}
};

/**
 * @brief Linear interpolation on a fan curve.
 *
 * Shared helper used by FanControlLogic.
 */
inline int32_t interpolateCurve( const std::vector< FanCurvePoint > &curve,
                                 int32_t temp ) noexcept
{
  if ( curve.empty() )
    return -1;

  if ( temp <= curve.front().temp )
    return curve.front().speed;

  for ( size_t i = 1; i < curve.size(); ++i )
  {
    const auto &prev = curve[i - 1];
    const auto &cur  = curve[i];

    if ( temp == cur.temp )
      return cur.speed;

    if ( temp > prev.temp && temp < cur.temp )
    {
      int32_t dt = cur.temp - prev.temp;
      if ( dt == 0 )
        return prev.speed;
      double frac = static_cast< double >( temp - prev.temp ) / static_cast< double >( dt );
      return static_cast< int32_t >(
        std::lround( prev.speed + frac * ( cur.speed - prev.speed ) ) );
    }
  }

  return curve.back().speed;
}

// ---------------------------------------------------------------------------
//  Fan zone
// ---------------------------------------------------------------------------

/**
 * @brief A group of fans sharing one thermal source and one fan curve.
 *
 * The zone is the primary unit of fan control.  FanControlWorker runs one
 * FanControlLogic instance per zone (not per fan), and applies the computed
 * speed to all fans in the zone.
 *
 * Zones are auto-generated after HAL detection based on fan labels and
 * device types.  Users can reassign fans between zones and edit per-zone
 * curves in the GUI.  The zone layout is stored per-profile.
 */
struct FanZone
{
  std::string id;                           ///< "zone-cpu", "zone-case", ...
  std::string name;                         ///< "CPU Fans", "Case Fans", ...
  std::vector< std::string > fanIds;        ///< FanInfo::id references
  std::string thermalSourceId;              ///< ThermalSource::id
  FanDeviceType defaultType = FanDeviceType::Fan;

  /// Temp → speed curve for this zone.
  std::vector< FanCurvePoint > curve;

  /// Per-zone hysteresis (degrees).
  int hysteresisDeg = 3;

  /// When false, fans in this zone are left in auto / firmware mode.
  bool enabled = true;
};

// ---------------------------------------------------------------------------
//  Fan zone curve — per-profile data (lightweight)
// ---------------------------------------------------------------------------

/**
 * @brief Per-zone curve settings stored inside a FanProfile.
 *
 * This is the lightweight per-profile data: just the curve, hysteresis,
 * enable flag, and an optional thermal-source override.  The full zone
 * topology (fanIds, name, deviceType) lives in FanZone and is owned by
 * HardwareManager.
 */
struct FanZoneCurve
{
  std::string zoneId;                         ///< matches FanZone::id
  std::vector< FanCurvePoint > curve;         ///< temp → speed mapping
  int hysteresisDeg = 3;                      ///< degrees of hysteresis
  bool enabled = true;                        ///< zone active in this profile
  std::string thermalSourceId;                ///< optional override (empty = hw default)

  FanZoneCurve() = default;

  FanZoneCurve( const std::string &id,
                std::vector< FanCurvePoint > c,
                int hyst = 3,
                bool en = true,
                const std::string &tsId = {} )
    : zoneId( id )
    , curve( std::move( c ) )
    , hysteresisDeg( hyst )
    , enabled( en )
    , thermalSourceId( tsId )
  {}
};

} // namespace ucc::hal
